In [1]:
import numpy as np
day_number=np.arange(1,11)
steps_walked=[4335,9552,7332,4504,5335,7552,8332,6504,8965,7689]
arr=np.array([day_number,steps_walked])
arr=arr.T
arr


array([[   1, 4335],
       [   2, 9552],
       [   3, 7332],
       [   4, 4504],
       [   5, 5335],
       [   6, 7552],
       [   7, 8332],
       [   8, 6504],
       [   9, 8965],
       [  10, 7689]])

In [2]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  6335],
       [    2, 11552],
       [    3,  9332],
       [    4,  6504],
       [    5,  7335],
       [    6,  9552],
       [    7, 10332],
       [    8,  8504],
       [    9, 10965],
       [   10,  9689]])

In [4]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2, 11552],
       [    3,  9332],
       [    6,  9552],
       [    7, 10332],
       [    9, 10965],
       [   10,  9689]])